server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${CONTEXT}
spring:
  datasource:
    driver-class-name: ${HIBERNATE_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_USER_PASSWORD}
  jpa:
    generate-ddl: true
    database-platform: ${DIALECT}
    hibernate:
      dialect: ${DIALECT}
      ddl-auto: update
google-maps:
  api-key: ${GOOGLE_MAPS_API_KEY}
