server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1
    username: root
    password: root
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
    show-sql: true
    open-in-view: false
google-maps:
  api-key: <API_KEY_GOOGLE_MAPS>
